title: Malayalam Poem Syllables duration
description: A dataset to model Malayalam poem syllable duration
publisher_text: Department of Computer Applications, Cochin University of Science and Technology, 682022
publisher_url: https://cusat.ac.in/

license_text: 
license_url: 
frequency: Monthly

certificate_embed: 
